# Generated by Django 5.2.3 on 2025-06-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_business",
            field=models.BooleanField(default=False),
        ),
    ]
