# Generated by Django 5.2.3 on 2025-06-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_data_board_likes_board_reviews_board_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='data',
            new_name='date',
        ),
    ]
